apps/frontend/src/components/common/FooterBar.tsx
apps/frontend/src/pages/index.tsx

fix: moving footbar to common folder

---

apps/frontend/src/components/LoginPage/LoginForm.tsx
apps/frontend/src/components/LoginPage/LoginPageContainer.tsx
apps/frontend/src/components/RegisterPage/RegisterForm.tsx
apps/frontend/src/components/RegisterPage/RegisterPageContainer.tsx
apps/frontend/src/context/NotificationContext.tsx
apps/frontend/src/hooks/useLoginForm.ts
apps/frontend/src/hooks/useRegisterForm.ts
apps/frontend/src/hooks/useSnackbar.ts
apps/frontend/src/pages/_app.tsx

-
- Implement Per page notification system
- Implement Notification Context
- Remove demo loading in login page and register page
-

Frontend/notification 

---

package.json
turbo.json

- Add testing in monorepo
- Add testing in monorepo
-
-

feat: add testing in monorepo

---

apps/backend/package.json
apps/backend/src/auth/auth.controller.ts
apps/backend/src/auth/auth.service.mock.ts
apps/backend/src/auth/auth.service.ts
apps/backend/src/guides/guides.controller.ts
apps/backend/src/guides/guides.service.ts
apps/backend/src/reviews/reviews.controller.ts
apps/backend/src/reviews/reviews.service.ts
apps/backend/src/users/users.controller.ts
apps/backend/src/users/users.service.ts
apps/frontend/package.json
package.json
packages/types/package.json
packages/types/src/dtos/auth/auth.dto.ts
packages/types/src/dtos/auth/index.ts
packages/types/src/dtos/guide/index.ts
packages/types/src/dtos/guide/searchGuide.dto.ts
packages/types/src/dtos/index.ts
packages/types/src/dtos/review/createReview.dto.ts
packages/types/src/dtos/review/index.ts
packages/types/src/dtos/user/createUser.dto.ts
packages/types/src/dtos/user/getUserById.dto.ts
packages/types/src/dtos/user/index.ts
packages/types/src/dtos/user/updateUserProfile.dto.ts
packages/types/src/index.ts
packages/types/tsconfig.json
pnpm-lock.yaml

- Refactor dto to  types packages

chore: refactor dto file to types packages

---

packages/types/src/dtos/bookings/acceptBooking.dto.ts
packages/types/src/dtos/bookings/createBooking.dto.ts
packages/types/src/dtos/bookings/declineBooking.dto.ts
packages/types/src/dtos/bookings/getBookings.dto.ts
packages/types/src/dtos/bookings/index.ts
packages/types/src/dtos/bookings/updateBooking.dto.ts
packages/types/src/dtos/guide/getGuideById.dto.ts
packages/types/src/dtos/guide/getGuideReviews.dto.ts
packages/types/src/dtos/guide/index.ts
packages/types/src/dtos/index.ts
packages/types/src/dtos/posts/createPost.dto.ts
packages/types/src/dtos/posts/deletePost.dto.ts
packages/types/src/dtos/posts/index.ts
packages/types/src/dtos/posts/updatePost.dto.ts

- Implement Boiler Plate for DTOS

chore(types): implement dtos boiler plate

---

apps/backend/src/main.ts
apps/frontend/next.config.js
apps/frontend/src/context/AuthContext.tsx
apps/frontend/src/context/type/authContext.ts
apps/frontend/src/hooks/useRegisterForm.ts
apps/frontend/src/pages/index.tsx
apps/frontend/src/pages/testGuard.tsx
apps/frontend/src/utils/apiClient.ts
apps/frontend/src/utils/checkRefresh.ts
apps/frontend/src/utils/interceptor.ts
packages/config/src/frontend.config.ts
packages/types/src/dtos/auth/auth.dto.ts
pnpm-lock.yaml

- Implement Auth Provider which send user data to every component. 
-
- Update axios interceptors's logic to refresh new access token when expired.
-

[Feature] Implement frontend auth context + AuthProvider

---

apps/backend/src/bookings/bookings.common.ts
apps/backend/src/bookings/bookings.controller.ts
apps/backend/src/bookings/bookings.module.ts
apps/backend/src/bookings/bookings.repository.ts
apps/backend/src/bookings/bookings.service.spec.ts
apps/backend/src/bookings/bookings.service.ts
packages/types/src/dtos/bookings/acceptBooking.dto.ts

- Add new route in bookings, accept and decline route
- Two new route POST `/bookings/{id}/accept`, `/bookings/{id}/decline`

feat(backend): implement bookings accept decline endpoints

---

.github/workflows/deploy-backend-image.yml
.github/workflows/deploy-frontend-image.yml

fix: run github action on pr

---

apps/backend/src/reviews/reviews.controller.ts
packages/types/src/dtos/review/createReview.dto.ts

[Fix] Create Review

---

apps/frontend/src/components/traveller-record/containerRecord.tsx
apps/frontend/src/components/traveller-record/data/mockData.ts
apps/frontend/src/components/traveller-record/data/recordType.ts
apps/frontend/src/components/traveller-record/data/sorting.ts
apps/frontend/src/components/traveller-record/data/statusHandle.ts
apps/frontend/src/components/traveller-record/dialogStatus.tsx
apps/frontend/src/components/traveller-record/index.tsx
apps/frontend/src/components/traveller-record/tableShow/content.tsx
apps/frontend/src/components/traveller-record/tableShow/contentDescription.tsx
apps/frontend/src/components/traveller-record/tableShow/headTable.tsx
apps/frontend/src/components/traveller-record/tableShow/table.tsx
apps/frontend/src/config/theme.ts
apps/frontend/src/pages/traveller-record/[id].tsx

fix: import error

---

apps/backend/src/reviews/reviews.controller.ts
packages/types/src/dtos/review/createReview.dto.ts

docs: update documentation

---

apps/backend/src/guides/guides.repository.ts

fix: fix SQL query

---

apps/backend/src/media/file.validators.ts
apps/backend/src/media/media.controller.ts
packages/media-storage/src/storages/local.media-storage.ts

fix: file upload error

---

apps/frontend/src/components/guide-register/chipArray.tsx
apps/frontend/src/components/guide-register/containerRecord.tsx
apps/frontend/src/components/guide-register/form.tsx
apps/frontend/src/components/guide-register/index.tsx
apps/frontend/src/constants/RegisterGuidePage/index.ts
apps/frontend/src/hooks/useRegisterGuideForm.tsx
apps/frontend/src/pages/guide-register/[id].tsx

Frontend register guide

---

packages/database/prisma/migrations/20230326160225_remove_booking_status/migration.sql

chore: generate SQL migration script

---

apps/backend/src/bookings/bookings.repository.ts
apps/backend/src/bookings/bookings.service.ts
apps/backend/src/guides/guides.repository.ts
apps/backend/src/guides/guides.service.ts

[PATCH] make it buildable

---

apps/backend/src/bookings/bookings.controller.ts
apps/backend/src/bookings/bookings.service.ts

refactor: remove line

---

apps/frontend/next.config.js

feat: finally connect .env to next.js

---

Dockerfile.backend
Dockerfile.frontend

Lock pnpm version in Dockerfile

---

apps/backend/src/bookings/bookings.service.ts
apps/backend/src/guides/guides.controller.ts
apps/backend/src/guides/guides.service.ts
apps/backend/src/media/media.controller.ts
apps/backend/src/media/media.service.ts
packages/types/src/dtos/guide/guideRegister.dto.ts
packages/types/src/dtos/media/upload.dto.ts

Backend profile refactor

---

apps/frontend/src/hooks/usePostForm.ts

fix: add more constraints

---

apps/frontend/next.config.js
apps/frontend/package.json
apps/frontend/src/components/payment-summary/PaymentOption.tsx
apps/frontend/src/components/payment-summary/StatusDisplayView.tsx
apps/frontend/src/components/payment-summary/Summary.tsx
apps/frontend/src/components/payment-summary/index.tsx
apps/frontend/src/components/payment-summary/types/index.ts
apps/frontend/src/components/payment-summary/useOmiseFrontend.tsx
apps/frontend/src/pages/payment-summary/[id].tsx
pnpm-lock.yaml

- Add UI and its connecting API
- Implement Payment Summary
-
-

[Frontend] Payment Summary

---

apps/frontend/src/components/managetrip-guide/NewRequest.tsx

fix: new request

---

apps/backend/src/bookings/bookings.service.ts
packages/types/src/dtos/bookings/cancelBookingByGuide.dto.ts

fix: add refund when guide cancel

---

apps/frontend/next.config.js
package.json
packages/config/src/frontend.config.ts
pnpm-lock.yaml
turbo.json

fix: change to dotenv-mono

---

apps/frontend/src/components/SearchPage/PostCard/OptionMenu.tsx

-
-
- Take edit-button back at search page (the edit feature is linked with tan's feature)
-

fix: take edit button back

---

apps/frontend/next.config.js
apps/frontend/src/components/SearchPage/PostCard/BookingModal.tsx
apps/frontend/src/components/payment-summary/index.tsx
apps/frontend/src/components/payment-summary/useOmiseFrontend.tsx
apps/frontend/src/components/traveller-record/tableShow/table.tsx
apps/frontend/src/components/traveller-record/tableShow/viewModel/booking.tsx
apps/frontend/src/hooks/useSearchPosts.ts
apps/frontend/src/pages/managetrip-guide.tsx

-
-
- fix conflict due to backend's pagination feature
-

fix: fix conflict due to backend's pagination feature

---

apps/backend/src/bookings/bookings.service.ts
apps/frontend/src/components/managetrip-guide/Content.tsx
packages/types/src/dtos/bookings/booking.dto.ts
packages/types/src/dtos/bookings/createBooking.dto.ts

Manage guide

---

apps/backend/src/bookings/bookings.service.ts
packages/types/src/dtos/bookings/cancelBookingByGuide.dto.ts

Backend the last commit

---

apps/frontend/src/components/SearchPage/FilterForm/SliderInput.tsx
apps/frontend/src/components/SearchPage/FilterForm/index.tsx
apps/frontend/src/components/SearchPage/index.tsx
apps/frontend/src/components/SearchPage/types/index.ts
apps/frontend/src/constants/SearchPage/index.ts
apps/frontend/src/hooks/useFilterForm.ts
apps/frontend/src/hooks/useSearchPosts.ts

-
- add page limitation due to the providing PostCount on Backend
- add ui for error response when fee < 30
- refactor some constant
- refactor fetching code
- extract fee and rating constant 
-

[FRONTEND] Update Search page features

---

apps/frontend/src/components/guide-profile/Content.tsx
apps/frontend/src/components/guide-profile/ReviewHead.tsx
apps/frontend/src/pages/guide-profile/[id].tsx

feat: redesign guide profile page

---

packages/database/prisma/migrations/20230403151057_add_user_image_profile/migration.sql
packages/database/prisma/migrations/20230403155338_add_image/migration.sql
packages/database/prisma/schema.prisma

chore: gen db script

---

apps/frontend/src/components/SearchPage/PostCard/CardHeader.tsx
apps/frontend/src/components/SearchPage/PostCard/OptionMenu.tsx
apps/frontend/src/components/SearchPage/PostCard/index.tsx
apps/frontend/src/hooks/useSearchPosts.ts

-
- add link to guide's profile
- set default page count is 1
-

[FRONTEND] feat: add link to guide profile

---

apps/frontend/src/components/payment-summary/index.tsx

[FRONTEND] fix: remove navbar in payment summary

---

apps/backend/src/bookings/bookings.service.ts

fix: cancel booking

---

apps/frontend/src/components/guide-profile/Profile.tsx
apps/frontend/src/components/guide-profile/Tags.tsx
apps/frontend/src/pages/guide-profile/[id].tsx

feat: add images(guide profile)

---

apps/frontend/src/components/SearchPage/PostCard/CardHeader.tsx
apps/frontend/src/components/SearchPage/index.tsx
apps/frontend/src/constants/SearchPage/index.ts
apps/frontend/src/hooks/useSearchPosts.ts

-
- add guide image in search page
-
-

feat: add guide image in search page

---

apps/backend/src/bookings/bookings.service.ts
apps/backend/src/guides/guides.repository.ts

Fix booking

---

apps/frontend/src/components/managetrip-guide/AcceptedRequest.tsx
apps/frontend/src/components/managetrip-guide/AcceptedRequestCard.tsx
apps/frontend/src/components/managetrip-guide/CanceledRequest.tsx
apps/frontend/src/components/managetrip-guide/CanceledRequestCard.tsx
apps/frontend/src/components/managetrip-guide/CompletedRequest.tsx
apps/frontend/src/components/managetrip-guide/CompletedRequestCard.tsx
apps/frontend/src/components/managetrip-guide/NewRequest.tsx
apps/frontend/src/components/managetrip-guide/NewRequestcard.tsx
apps/frontend/src/components/managetrip-guide/Types.tsx
apps/frontend/src/hooks/types/dashBoardState.ts
apps/frontend/src/hooks/useDashBoard.ts
apps/frontend/src/pages/managetrip-guide.tsx
apps/frontend/src/utils/dashboardUrlMapper.ts

fix: bugbugbug

---

apps/frontend/src/hooks/useSearchPosts.ts

-
-
- change : authorId is userId
-

fix: authorId is userId

---

apps/frontend/src/pages/guide-profile/[id].tsx

fix: style

---

apps/frontend/src/components/SearchPage/PostCard/BookingModal.tsx
apps/frontend/src/components/SearchPage/PostCard/CardContent.tsx
apps/frontend/src/components/SearchPage/PostCard/CardHeader.tsx
apps/frontend/src/components/SearchPage/PostCard/index.tsx
apps/frontend/src/components/SearchPage/types/index.ts
apps/frontend/src/constants/SearchPage/index.ts
apps/frontend/src/hooks/useSearchPosts.ts

-
-
- fix conflict between userId and GuideId
-

fix: fix conflict between userId and GuideId

---

apps/frontend/src/constants/SearchPage/index.ts
apps/frontend/src/hooks/useSearchPosts.ts
apps/frontend/src/pages/managetrip-guide.tsx

- [] New features
- [] Breaking changes
-
-
- fix guideId userId conflict
-

fix: fix guideId userId conflict in managerTrip and post search

---

apps/frontend/src/components/guide-profile/Content.tsx
apps/frontend/src/components/guide-profile/Profile.tsx
apps/frontend/src/components/guide-profile/ReviewHead.tsx
apps/frontend/src/pages/guide-profile/[id].tsx

fix: style again

---

apps/frontend/src/components/payment-summary/StatusDisplayView.tsx

feat: add auto navigate back to dashboard

---

apps/backend/src/bookings/bookings.service.ts
apps/frontend/src/components/payment-summary/StatusDisplayView.tsx

feat: fix traveling

---

apps/backend/src/bookings/bookings.controller.ts
apps/backend/src/bookings/bookings.service.ts
packages/types/src/dtos/auth/auth.dto.ts
packages/types/src/dtos/user/user.dto.ts

- Minor bug fix and improve api doc

fix: minor bug fix and improve api doc

---

apps/backend/src/bookings/bookings.service.ts

feat: fxxxxxxx

---

apps/frontend/src/components/LoginPage/index.tsx
apps/frontend/src/components/common/Navbar.tsx
apps/frontend/src/context/AuthContext.tsx
apps/frontend/src/hooks/useRegisterForm.ts
apps/frontend/src/utils/interceptor.ts

fix: fix redirect bugs after unauthorized bugs

---

apps/backend/src/reports/reports.common.ts
apps/backend/src/reports/reports.controller.ts
apps/backend/src/reports/reports.repository.ts
apps/backend/src/reports/reports.service.ts
packages/database/prisma/migrations/20230415081527_add_guide_id_and_post_id_to_report/migration.sql
packages/database/prisma/schema.prisma
packages/types/src/dtos/report/createReport.dto.ts
packages/types/src/dtos/report/getReport.dto.ts
packages/types/src/dtos/report/report.dto.ts

-Update Report model and DTOs
-You can send a report with guideId or postId as query params
-Update api doc

feat(backend): add guide, post id option to report

---

apps/backend/src/reports/reports.repository.ts
apps/backend/src/reports/reports.service.ts

fix: change reports count to be total count

---

apps/frontend/src/components/SearchPage/FilterForm/DateInput.tsx
apps/frontend/src/components/SearchPage/types/index.ts
apps/frontend/src/hooks/useFilterForm.ts

-
-
- input date now include time 
- remove unused code
-

fix: input date now include time, remove unused code

---

apps/frontend/src/components/guide-profile/Content.tsx
apps/frontend/src/components/guide-profile/Review.tsx

fix ui when review is long
-
-
-

fix: incorrect ui when review is long

---

apps/frontend/src/components/adminReport/content.tsx
apps/frontend/src/components/adminReport/tablePaginationActions.tsx
apps/frontend/src/components/adminReport/top.tsx
apps/frontend/src/pages/adminReport.tsx

Frontend admin report

---

apps/frontend/src/components/guide-profile/ReviewHead.tsx

fix: round review score

---

apps/frontend/src/components/adminReport/content.tsx
apps/frontend/src/components/managetrip-guide/AcceptedRequestCard.tsx
apps/frontend/src/components/managetrip-guide/CanceledRequestCard.tsx
apps/frontend/src/components/managetrip-guide/CompletedRequestCard.tsx
apps/frontend/src/components/managetrip-guide/NewRequestcard.tsx

fix: change datetime format

---

.github/workflows/test-backend.yml
apps/backend/src/bookings/bookings.controller.spec.ts
apps/backend/src/bookings/bookings.module.ts
apps/backend/src/bookings/bookings.service.spec.ts
apps/backend/src/bookings/bookings.service.ts
apps/backend/src/guides/guides.module.ts
apps/backend/src/guides/guides.repository.ts
apps/backend/src/guides/guides.service.ts
apps/backend/src/payment/payment.controller.ts
apps/backend/src/payment/payment.module.ts
apps/backend/src/payment/payment.repository.ts
apps/backend/src/payment/payment.service.ts
apps/backend/src/posts/posts.controller.spec.ts
apps/backend/src/posts/posts.module.ts
apps/backend/src/posts/posts.repository.ts
apps/backend/src/reports/reports.controller.spec.ts
apps/backend/src/reports/reports.controller.ts
apps/backend/src/reports/reports.module.ts
apps/backend/src/reports/reports.repository.ts
apps/backend/src/reviews/reviews.controller.ts
apps/backend/src/users/users.controller.spec.ts
apps/backend/src/users/users.controller.ts
apps/backend/src/users/users.e2e.spec.ts
apps/backend/src/users/users.service.spec.ts
apps/backend/src/users/users.service.ts
packages/types/src/dtos/user/updateUserProfile.dto.ts

- Add Unit Test, e2e Test for User Module
- Fix bug in user service

test(backend): implement unit and e2e test and fix bug

---

apps/frontend/src/components/guide-post/editViewModel.tsx
apps/frontend/src/components/guide-post/formEdit.tsx
apps/frontend/src/pages/guide-post/create.tsx
apps/frontend/src/pages/guide-post/edit/[id].tsx

fix: create/edit post permission

---

apps/frontend/src/components/payment-summary/useOmiseFrontend.tsx

-
-
- add placeholder error message for payment frontend
-

fix: add placeholder error message for payment frontend

---

apps/frontend/src/components/SearchPage/FilterForm/SliderInput.tsx
apps/frontend/src/components/SearchPage/FilterForm/index.tsx
apps/frontend/src/components/SearchPage/types/index.ts
apps/frontend/src/constants/SearchPage/index.ts
apps/frontend/src/hooks/useFilterForm.ts
apps/frontend/src/hooks/useSearchPosts.ts

-
-
- turn range input slider into single input
-

fix: turn range input slider into single input

---

apps/backend/src/posts/posts.repository.ts
apps/backend/src/posts/posts.service.ts

ขอให้เป็น commit สุดท้าย

---

apps/frontend/src/components/managetrip-guide/Content.tsx
apps/frontend/src/constants/SearchPage/index.ts
apps/frontend/src/hooks/useSearchPosts.ts

-
-
- frontend manageTripGuide 
- minRating default
-

fix: fix frontend manageTripGuide & minRating default

---

apps/backend/src/reviews/reviews.controller.spec.ts
apps/backend/src/reviews/reviews.controller.ts
apps/backend/src/reviews/reviews.service.spec.ts

- [* ] New features
-unit test for Reviews services and controller for creating a review

feat: add create review unit test

---

apps/frontend/src/components/SearchPage/FilterForm/index.tsx
apps/frontend/src/constants/SearchPage/index.ts

fix: default min rating

---

apps/backend/src/posts/posts.repository.ts

La Leaw La Lub Vicha SE Ya Dai Jher Kan Eek
